version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smartbot_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smart_bot_db
    ports:
      - "5432:5432":
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data

